/*Appium Assignment
  Mirnesa Hodzic, November 2021
  Test case 01 - Enter name, password and click the login button.
*/

/*Import the login screen POM*/
import { LoginScreenPom } from "./LoginScreenPom.js";

/*Import the webdriver IO. Classic JS, using import pkg*/
import pkg from "webdriverio";
const wdio = pkg;

/*Import strict assertion*/
import {strict as assert} from "assert";

/*Options, set to run the android application*/
const opts = {
  path: '/wd/hub',
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "7",
    deviceName: "Android Emulator",
    app: "..\\LoginApp\\app\\build\\outputs\\apk\\debug\\loginapp-debug.apk", //APK package generated by Android studio
    appPackage: "org.mirnesa.loginapp",                                       //Java package of the androind application 
    appActivity: ".ui.login.LoginActivity",                                   //Activity name specified in the Android manifest
    automationName: "UiAutomator2"                                            //Automation system for testing UIs
  }
};

/*Constants for the tests*/
const USER_NAME = 'user001@gmail.com';
const USER_PASSWORD = '123456';


/*The test case steps*/
async function test01 () {

  /*Connect to the webdriverio*/
  const client = await wdio.remote(opts);

  /*Instantiate the pom*/
  var loginScreen = new LoginScreenPom(client);
  
  /*Enter name and password*/
  await loginScreen.enterName(USER_NAME);
  await loginScreen.enterPassword(USER_PASSWORD);
  
  /*Check if the name and password are entered in the fields*/
  const vName = await loginScreen.getEnteredName();
  const vPassword = await loginScreen.getEnteredPassword();

  /*The name field should be displayed with the name entered*/
  assert.strictEqual(vName,USER_NAME);
  /*The password is not to be openly shown, dots instead*/
  assert.notStrictEqual(vPassword,USER_PASSWORD);

  /*Ascertain that the login button is enabled*/
  const btnEnabled = await loginScreen.isLoginButtonEnabled();
  assert.strictEqual(btnEnabled,true);

  /*Now click the button to login*/
  await loginScreen.clickLoginButton();

  /*Terminate the test and the session*/
  await client.deleteSession();
}

/*Execute the test case*/
test01();

